artifact_location: /home/vlee/repos/intel-mlops-certified-developer/MLOps_Professional/mlops_capstone/store/models/robot_maintenance/135581471619916663
creation_time: 1733740690541
experiment_id: '135581471619916663'
last_update_time: 1733740690541
lifecycle_stage: active
name: capstone_1
