aliases: []
creation_timestamp: 1733741104026
current_stage: Staging
description: ''
last_updated_timestamp: 1733741127398
name: H4E
run_id: 126855f117d4475089c8d7fe09d347e5
run_link: ''
source: /home/vlee/repos/intel-mlops-certified-developer/MLOps_Professional/mlops_capstone/store/models/robot_maintenance/135581471619916663/126855f117d4475089c8d7fe09d347e5/artifacts/model
status: READY
status_message: null
storage_location: /home/vlee/repos/intel-mlops-certified-developer/MLOps_Professional/mlops_capstone/store/models/robot_maintenance/135581471619916663/126855f117d4475089c8d7fe09d347e5/artifacts/model
user_id: null
version: 2
