artifact_uri: /home/vlee/repos/intel-mlops-certified-developer/MLOps_Professional/mlops_capstone/store/models/robot_maintenance/135581471619916663/1caec89c739048fbb9b985486f5a87ed/artifacts
end_time: 1733826521225
entry_point_name: ''
experiment_id: '135581471619916663'
lifecycle_stage: active
run_id: 1caec89c739048fbb9b985486f5a87ed
run_name: skittish-squid-874
run_uuid: 1caec89c739048fbb9b985486f5a87ed
source_name: ''
source_type: 4
source_version: ''
start_time: 1733826518206
status: 3
tags: []
user_id: vlee
