name: lab5
channels:
  - defaults
dependencies:
  - python=3.9.13  # Specify the Python version you want to use
  - pip
  - pip:
      - torch==2.0.0
      - torchvision==0.15.1
      - intel-extension-for-pytorch==2.0.0
      - py-cpuinfo
