name: lab5
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # Specify the Python version you want to use
  - pip
  - pip:
      - torch
      - torchvision
      - intel-extension-for-pytorch
      - py-cpuinfo
