channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=24.2
- pip:
  - mlflow==2.15.0
  - numpy==1.24.4
  - pandas==2.0.3
  - scikit-learn==1.3.2
  - scipy==1.10.1
  - xgboost==2.0.0
name: mlflow-env
